items_for_charity_foundation/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import CreateUser
from charity_app.views import LandingPage, AddDonation, ConfForm, DonationListView, UserProfilView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('register/', CreateUser.as_view(), name="register-view"),
    path("", LandingPage.as_view(), name="main-menu"),
    path("form/", AddDonation.as_view(), name="form-view"),
    path("form_com/", ConfForm.as_view(), name="comf-view"),
    path("doantions/", DonationListView.as_view(), name="donation-listview"),
    path("profil_details/", UserProfilView.as_view(), name="profil-view"),
]

accounts/models.py
from django.db import models

# Create your models here.

charity_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=254, null=True)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=254)
    description = models.TextField()
    FOUNDATION = {
        (1, "fundacja"),
        (2, "organizacja pozarządowa"),
        (3, "zbiórka lokalna"),
    }
    type = models.IntegerField(choices=FOUNDATION, default=1)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category, null=True, blank=True)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.TextField()
    phone_number = models.PositiveIntegerField()
    city = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=6)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.TextField()
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} przekazał {self.institution}, ilość worków: {self.quantity}"

accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from accounts.form import SignUpForm


class CreateUser(View):

    def get(self, request):
        form = SignUpForm()
        return render(request, "registration/register.html", {"form": form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = request.POST.get('first_name') + " " + request.POST.get('last_name')
            user = User.objects.create(username=request.POST.get("email"),
                                       first_name=request.POST.get("first_name"),
                                       last_name=request.POST.get("last_name"),
                                       email=request.POST.get("email"))
            user.set_password(request.POST.get("password1"))
            user.save()
            return redirect("/login")
        return render(request, 'registration/register.html', {'form': form})

charity_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import DetailView, ListView

from charity_app.form import MainForm
from charity_app.models import Institution, Donation, Category


class LandingPage(View):

    def get(self, request):
        foundList = Institution.objects.all().filter(type=1)
        nationalOffList = Institution.objects.all().filter(type=2)
        localList = Institution.objects.all().filter(type=3)
        sumLst = len(foundList) + len(nationalOffList) + len(localList)
        sum_packages = 0
        for pack in Donation.objects.all():
            sum_packages += int(pack.quantity)
        paginator1 = Paginator(foundList, 3)
        paginator2 = Paginator(nationalOffList, 3)
        paginator3 = Paginator(localList, 3)
        page_number1 = request.GET.get("page")
        page_obj1 = paginator1.get_page(page_number1)
        page_number2 = request.GET.get("page")
        page_obj2 = paginator2.get_page(page_number2)
        page_number3 = request.GET.get("page")
        page_obj3 = paginator3.get_page(page_number3)
        return render(request, "index.html", {"found": page_obj1, "offn": page_obj2, "local_found": page_obj3,
                                              "sum_lst": sumLst, "sum_pack": sum_packages
                                              })


class AddDonation(View):

    def get(self, request):
        form = MainForm()
        categories = Category.objects.all()
        institutions = Institution.objects.all()
        return render(request, "form.html", {"form": form, "categories": categories, "institutions": institutions})

    def post(self, request):
        form = MainForm(request.POST)
        if form.is_valid():
            quantity = request.POST.get("bags")
            institution = request.POST.get("organization")
            address = request.POST.get("address")
            phone_number = request.POST.get("phone")
            city = request.POST.get("city")
            zip_code = request.POST.get("post_code")
            pick_up_date = request.POST.get("data")
            pick_up_time = request.POST.get("time")
            pick_up_comment = request.POST.get("more_info")
            user = self.request.user
            donation = Donation.objects.create(quantity=quantity,
                                               institution=Institution.objects.get(name=institution),
                                               address=address, phone_number=phone_number, city=city,
                                               zip_code=zip_code, pick_up_date=pick_up_date,
                                               pick_up_time=pick_up_time, pick_up_comment=pick_up_comment, user=user)
            donation.save()
            return redirect("/form_com/")
        else:
            return HttpResponse(f'Upss... coś poszło nie tak!')


class ConfForm(View):
    def get(self, request):
        return render(request, "form-confirmation.html")


class DonationListView(LoginRequiredMixin, ListView):
    def test_func(self):
        pk = self.kwargs['pk']
        try:
            self.model.objects.get(user=self.request.user, pk=pk)
            return True
        except self.model.DoesNotExist:
            return False

    model = Donation
    template_name = "donations_listview.html"


class UserProfilView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "profil_detail.html"

    def get_object(self, queryset=None):
        self.object = self.request.user
        return self.object

charity_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css" />

</head>
<body>
    <header class="header">
            {% if not user.is_authenticated %}
                <ul class="nav--actions">
                  <a href="/login/" class="btn btn--small btn--without-border">Zaloguj</a>
                  <a href="/register/" class="btn btn--small btn--highlighted">Załóż konto</a>
                </ul>
            {% elif user.is_authenticated  %}
                <div id="menu_roll">
                    <ul class="nav--actions">
                        Witaj, {{ user.first_name }}!
                        <div><a>Więcej</a>
                            <ul class="group" id="sub_menu">
                                <a href="/profil_details/" class="btn btn--small btn--without-border">Profil</a>
                                <a href="/doantions/" class="btn btn--small btn--without-border">Moje donacje</a>
                                <a href="/logout/" class="btn btn--small btn--without-border">Wyloguj</a>
                            </ul>
                        </div>
                    </ul>
                </div>

            {% endif %}
<nav class="container container--70">
        <ul>
          <li><a href="/" class="btn btn--without-border active">Start</a></li>
          <li><a href="/#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="/#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="{% if user.is_authenticated %}{% url "form-view" %}{% elif not user.is_authenticated %}{% url 'login' %}{% endif %}" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="/#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>
    </header>

{% block content %}
{% endblock %}

    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
          <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

          <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src="/static/images/icon-facebook.svg"/></a>
          <a href="#" class="btn btn--small"><img src="/static/images/icon-instagram.svg"/></a>
        </div>
      </div>
    </footer>

    <script src="/static/js/app.js"></script>
</body>
</html>

charity_app/templates/donation_detail.html
{% extends "base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="jumbotron">
            <h1>{{ donation.pk }}</h1>
            <p1>{{ donation.quantity }}</p1>
            <p1>{{ donation.categories }}</p1>
            <p1>{{ donation.institution }}</p1>
            <p1>{{ donation.address }}</p1>
            <p1>{{ donation.phone_number }}</p1>
            <p1>{{ donation.city }}</p1>
            <p1>{{ donation.zip_code }}</p1>
            <p1>{{ donation.pick_up_date }}</p1>
            <p1>{{ donation.pick_up_time }}</p1>
            <p1>{{ donation.pick_up_comment }}</p1>
            <div class="container">
                <a class="btn btn-dark" href="{{ delivery.get_edit_url }}"> Edytuj dane</a>
                <a class="btn btn-danger" href="{{ delivery.get_delete_url }}"> Usuń</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

charity_app/templates/donations_listview.html
{% extends "base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="jumbotron">
            <ul>Twoje donacje
                {% for donation in user.donation_set.all %}
                    <li>{{ donation }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

charity_app/templates/form-confirmation.html
{% extends "base.html" %}
{% block content %}
  <body>
      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
  </body>
{% endblock %}

charity_app/templates/form.html
{% extends "base.html" %}
 {% block content %}
  <body>
    <header class="header--form-page">
      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br>
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form method="POST"  name="myForm" id="form" onclick="validate();">
        {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
            {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="{{ category.name }}" class="required">
                <span class="checkbox"></span>
                <span class="description">{{ category.name }}, {{ category.description }}</span>
              </label>
            </div>
              {% endfor %}
            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" id="bags" name="bags" step="1" min="1" class="required">
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
            {% for inst in institutions %}
            <div class="form-group form-group--checkbox" id="organization_div">
              <label>
                <input type="radio" name="organization" id="{{ inst.name }}" value="{{ inst.name }}" class="required">
                <span class="checkbox radio"></span>

                <span class="description">
                  <div class="title">{{ inst.name }}</div>
                  <div class="subtitle">Cel i misja: Pomoc {{ inst.description }}</div>
                </span>
              </label>
            </div>
              {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input id="adres" type="text" name="address" class="required"> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input  id="city" type="text" name="city" class="required"> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input id="post_code" type="text" name="post_code" class="required">
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input id="phone_n" type="phone" name="phone" class="required">
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input id="pick_up_date" type="date" name="data" class="required"></label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input id="pick_up_hour" type="time" name="time" class="required"></label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea id="for_delivery" name="more_info" rows="5" class="required"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span id="bags_quantity" class="summary--text"></span>
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span id="foundation_name" class="summary--text"></span>
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li id="adres_out"></li>
                    <li id="city_out"></li>
                    <li id="post_code_out"></li>
                    <li id="phone_n_out"></li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li id="pick_up_out"></li>
                    <li id="time_out"></li>
                    <li id="for_deliver_out"></li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>
  </body>
{% endblock %}

charity_app/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <body>
  <header class="header--main-page">
  <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
  </header>
    <section id="stats" class="stats">

      <div class="container container--85">
        <div class="stats--item">
          <em>{{ sum_pack }}</em>
          <h3>Oddanych worków</h3>
          <p>Dziękujemy za przekazanie wszystkich darów!</p>
        </div>

        <div class="stats--item">
          <em>{{ sum_lst }}</em>
          <h3>Wspartych organizacji</h3>
          <p>Dziękujemy! Bez pomocy organizacji nie byłoby możliwości pomocy.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'register-view' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Jesteśmy stroną tworzącą przestrzeń, dzięki której użytkownik będzie mógł w prosty i szybki sposób oddać swoje niechciane rzeczy zaufanym instytucjom.</p>
        <img src="../../static/images/signature.svg" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="../../static/images/about-us.jpg" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

        <ul class="help--slides-items">
            {% for item in found %}
          <li>
            <div class="col">
              <div class="title">{{ item.name }}</div>
              <div class="subtitle">{{ item.description }}</div>
            </div>

            <div class="col"><div class="text">{{ item.categories }}</div></div>
          </li>
            {% endfor %}
        </ul>
        <ul class="help--slides-pagination">
        {% if plans.has_previous %}
            <a class="text-dark" href="?page={{ plans.previous_page_number }}">< poprzednia</a>
        {% endif %}
        {% for n in plans.paginator.page_range %}
            {% if plans.number == n %}
                <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">{{ n }}</a></li>
            {% elif n > plans.number|add:'-4' and n < plans.number|add:'4' %}
                <li><a href="?page={{ n }}" class="btn btn--small btn--without-border active" data-page="1">| {{ n }} |</a></li>
            {% endif %}
        {% endfor %}
        {% if plans.has_next %}
            <a class="text-dark" href="?page={{ plans.next_page_number }}">następna ></a>
        {% endif %}
{#          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>#}
{#          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>#}
{#          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>#}
        </ul>

      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Pomagamy również wszelkim organizacjom pozarządowym i charytatywnym, które nie są Fundacjami. Są to nasi Partnerzy, który zrobią dobry pożytek z rzeczy, które do nich trafią.
        </p>
        <ul class="help--slides-items">
           {% for item in offn %}
          <li>
            <div class="col">
              <div class="title">{{ item.name }}</div>
              <div class="subtitle">{{ item.description }}</div>
            </div>

            <div class="col"><div class="text">{{ item.categories }}</div></div>
          </li>
            {% endfor %}
        </ul>

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
        </ul>
        -->
      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Wspieramy lokalne zbiórki organizowane przez indywidualne osoby, którym zależy na dobru społeczności, w której żyją. Sam też możesz zorganizować taką zbiórkę i pomóc tym, którzy są najbliżej.</p>
        <ul class="help--slides-items">
          {% for item in local_found %}
          <li>
            <div class="col">
              <div class="title">{{ item.name }}</div>
              <div class="subtitle">{{ item.description }}</div>
            </div>

            <div class="col"><div class="text">{{ item.categories }}</div></div>
          </li>
            {% endfor %}
        </ul>

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
        </ul>
        -->
      </div>
    </section>
    <script src="/static/js/app.js"></script>
  </body>
{% endblock %}

charity_app/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="#" class="btn btn--without-border">Załóż konto</a>      
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>
{% endblock %}

charity_app/templates/profil_detail.html
{% extends "base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="jumbotron">
            <h1>Nazwa użytkownika: {{ user }}</h1>
            <p1>Dane konta</p1>
        </div>
            <ul class="list-group">
                <li class="list-group-item">Imie: {{ user.first_name }}</li>
                <li class="list-group-item">Nazwisko: {{ user.last_name }}</li>
                <li class="list-group-item">email: {{ user.email }}</li>
            </ul>
        <a class="btn btn-dark" href="/edit_user/"> Edytuj Dane osobowe</a>
        <a class="btn btn-dark" href="/edit_profil/"> Edytuj Adres i tel</a>
        <a class="btn btn-warning" href="/password_change/"> Zmień hasło</a>
        <a class="btn btn-danger" href="/del_profil/"> Usuń</a>
    {% endif %}
{% endblock %}

charity_app/templates/register.html
{% extends "base.html" %}
{% block content %}
    <section class="login-page">
      <h2>Załóż konto</h2>
      <form>
        <div class="form-group">
          <input type="text" name="name" placeholder="Imię" />
        </div>
         <div class="form-group">
          <input type="text" name="surname" placeholder="Nazwisko" />
        </div>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
        </div>
        <div class="form-group">
          <input type="password" name="password2" placeholder="Powtórz hasło" />
        </div>

        <div class="form-group form-group--buttons">
          <a href="login.html" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>
{% endblock %}